#index:
#    path: /
#    controller: App\Controller\DefaultController::index
api_pay_sales_departmentexport_csv:
  path: /pay/sales-department/export
  controller: App\Controller\PayController::exportAction
  methods: [GET]